# Generated by Django 3.1.6 on 2021-03-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('i', 'Ingreso'), ('g', 'Gasto')], default='i', max_length=1),
            preserve_default=False,
        ),
    ]
